# Generated by Django 3.0.4 on 2022-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', max_length=300, upload_to=''),
            preserve_default=False,
        ),
    ]
